"""Fold web/ into one self-contained HTML file that works from file://.

Each module keeps its own scope, in an IIFE that returns its namespace. That
matters: concatenating three files that each define helpers like `$` or
`round4` into one scope would collide silently, and a silent collision in a
calculator is exactly the failure mode this project exists to avoid.
"""
import re, sys, pathlib

WEB = pathlib.Path('web')
data = (WEB / 'data.js').read_text()
engine = (WEB / 'engine.js').read_text()
app = (WEB / 'app.js').read_text()
html = (WEB / 'index.html').read_text()
css = (WEB / 'styles.css').read_text()


def export_names(src):
    names = set(re.findall(
        r'^export\s+(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)',
        src, re.M))
    for blk in re.findall(r'^export\s*\{([^}]*)\}', src, re.M):
        for part in blk.split(','):
            part = part.strip()
            if part:
                names.add(part.split(' as ')[-1].strip())
    return sorted(names)


DATA_NAMES = export_names(data)
ENGINE_NAMES = export_names(engine)

# Strip module syntax. `export ` only ever prefixes a declaration here.
data_body = re.sub(r'^export\s+', '', data, flags=re.M)
engine_body = re.sub(r"^import\s*\{[^}]*\}\s*from\s*'\./data\.js';", '',
                     engine, flags=re.M)
engine_body = re.sub(r'^export\s+', '', engine_body, flags=re.M)

# The engine pulls 42 names out of data.js; hand them in by destructuring.
imported = re.search(r"^import\s*\{([^}]*)\}\s*from\s*'\./data\.js';",
                     engine, re.M).group(1)
imported = [x.strip() for x in imported.replace('\n', ' ').split(',') if x.strip()]
missing = [n for n in imported if n not in DATA_NAMES]
if missing:
    sys.exit(f'engine imports names data.js does not export: {missing}')

# app.js loads its two modules dynamically so a missing engine produces an
# explanation rather than a blank page. In a bundle there is nothing to fetch.
app_body, n = re.subn(
    r'try \{\s*\[DATA, ENGINE\] = await Promise\.all\(\[\s*'
    r"import\('\./data\.js'\),\s*import\('\./engine\.js'\),\s*\]\);\s*"
    r'\} catch \(err\) \{\s*showFatal\(err, \'load\'\);\s*\}',
    'DATA = __DATA__; ENGINE = __ENGINE__;', app)
if n != 1:
    sys.exit(f'could not find app.js\'s dynamic loader (matched {n} times)')

bundle = f"""/* Bundled from web/ — data.js, engine.js, app.js, in that order.
   Generated by scripts/bundle.py; edit the sources, not this file. */
const __DATA__ = (() => {{
{data_body}
return {{ {', '.join(DATA_NAMES)} }};
}})();

const __ENGINE__ = (() => {{
const {{ {', '.join(imported)} }} = __DATA__;
{engine_body}
return {{ {', '.join(ENGINE_NAMES)} }};
}})();

await (async () => {{
{app_body}
}})();
"""

out = html.replace('<link rel="stylesheet" href="./styles.css">',
                   f'<style>\n{css}\n</style>')
if out == html:
    sys.exit('stylesheet link not found')
out2 = out.replace('<script type="module" src="./app.js"></script>',
                   f'<script type="module">\n{bundle}\n</script>')
if out2 == out:
    sys.exit('app.js script tag not found')

dest = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'battle-calculator.html')
dest.write_text(out2)
print(f'{dest}  {len(out2):,} bytes  '
      f'({len(DATA_NAMES)} data exports, {len(ENGINE_NAMES)} engine exports)')
